#!/bin/sh

# Non-destructive: after committing, ignored changes
# won't get erased.
# Markers:
#
# gitignore_start(UPPERCASE)
# lines here
# will be
# ignored
# gitignore_end(UPPERCASE)

set -e

tmpdir=$(mktemp -d)

cleanup() {
  rm -rf "$tmpdir"
}

trap cleanup EXIT

files=$(git diff --cached --name-only --diff-filter=ACM)

for file in $files; do
  [ -f "$file" ] || continue

  # Save original local version
  cp "$file" "$tmpdir/original"

  # Remove ignored lines
